# Generated by Django 3.0.6 on 2020-05-09 03:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Printer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('printer_name', models.CharField(help_text='Name of printer on server. Example: IT Copier OR 8x11_1125.', max_length=75, verbose_name='Printer Name')),
                ('printer_model_name', models.CharField(help_text='Printer model name. Example: HP LaserJet m402dn.', max_length=75, verbose_name='Printer Model Name')),
                ('printer_location', models.CharField(help_text='Location of printer. Example: Building 8 Room 45 OR 8-45', max_length=50, verbose_name='Printer Location')),
                ('ip_address', models.CharField(help_text='IPv4 address of the printer.', max_length=15, verbose_name='IP Address')),
                ('department_name', models.CharField(help_text='What department is this printer in?', max_length=50, verbose_name='Department Name')),
            ],
        ),
        migrations.CreateModel(
            name='TonerLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('module_identifier', models.CharField(help_text='Identifier for the toners or units. Example. Magenta OR Toner Collection Unit.', max_length=20)),
                ('level', models.CharField(help_text='This should be either a percentage (0 - 100 without the percent sign) or OK or NA.', max_length=3)),
                ('printer_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Printer')),
            ],
        ),
    ]
