# Generated by Django 3.0.6 on 2020-05-18 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tonerlevel',
            name='module_identifier',
            field=models.CharField(help_text='Identifier for the toners or units. Example. Magenta OR Toner Collection Unit.', max_length=50),
        ),
    ]
