# Generated by Django 3.0.6 on 2020-06-08 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_printer_snmp_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printer',
            name='ip_address',
            field=models.CharField(help_text='IPv4 address of the printer.', max_length=15, unique=True, verbose_name='IP Address'),
        ),
    ]
